# See: https://www.dartlang.org/tools/pub/pubspec
name: sql_builder
version: 0.0.1
description: >-
  A fluent interface for constructing SQL queries using a programmatic
  domain-specific language instead of brittle string interpolation and
  concatenation.
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/sql_builder.dart
documentation:
dependencies:
dev_dependencies:
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
  sdk: '>=2.0.0 <3.0.0'
executables:
